package project_management.management;

import Data.DataController;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Tab;
import javafx.scene.control.TabPane;
import javafx.scene.control.TextField;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;
import javafx.scene.Node;
import Data.Project;

import java.io.IOException;
import java.util.ArrayList;



/**
 * Dashboard . Was autogenerated and i didn,'t change the name*/
public class HelloController {

    private Scene scene; // for the change windows
    private Stage stage; // for the change windows
    private Parent parent; // for the change windows

    @FXML
    private TabPane projectTabPane; // refers to the tabpane on the window
    private int tabCounter=0; // how many tabs are

    @FXML
    private TextField projectName; // refers to the project name filed in the window

    /**
     * Action when clicking New
     * here we load the template of Projecttabcontroller where we can
     * put all the infotmation required to appera in the frontpage*/
    @FXML
    protected void onNewButtonClick() throws IOException{
        if( projectName.getText().isEmpty()) return;
        Project p = new Project(projectName.getText());
        DataController.getInstance().getProjetcs().add(p);
        tabCounter++;
        FXMLLoader loader = new FXMLLoader(getClass().getResource("ProjectTab-view.fxml"));
        AnchorPane tabContent = loader.load();
        ProjectTabController tabController = loader.getController();
        tabController.setTabContent(tabCounter,p);
        Tab newTab = new Tab(projectName.getText(),tabContent);
        projectTabPane.getTabs().add(newTab);
        projectName.setText("");
    }
    /**
     * Delete the current project and corresponding tab*/
    @FXML
    protected void onDeleteButtonClick(){
        if(projectTabPane.getTabs().isEmpty()) return;
        int index = projectTabPane.getSelectionModel().getSelectedIndex();
        DataController.getInstance().getProjetcs().remove(index);
        projectTabPane.getTabs().remove(index);
    }

    /**
     * Open a new window with the information of the project */
    @FXML
    protected void onOpenButtonClick(ActionEvent e) throws IOException {
        FXMLLoader loader = new FXMLLoader(getClass().getResource("Project-view.fxml"));
        parent = loader.load();
        ProjectController controller = loader.getController();
        controller.loadWindow(DataController.getInstance().getProjetcs().get(projectTabPane.getSelectionModel().getSelectedIndex()));
        stage = (Stage) ((Node)e.getSource()).getScene().getWindow();
        scene = new Scene(parent);
        stage.setScene(scene);
        stage.show();
    }

    /**
     * Function that must be used every time we load the window, information is
     * stored in Data controller so must be load in the window*/
    public void loadWindow() throws IOException {
        for (Project p : DataController.getInstance().getProjetcs()){
            tabCounter++;
            FXMLLoader loader = new FXMLLoader(getClass().getResource("ProjectTab-view.fxml"));
            AnchorPane tabContent = loader.load();
            ProjectTabController tabController = loader.getController();
            tabController.setTabContent(tabCounter,p);
            Tab newTab = new Tab(p.getName(),tabContent);
            projectTabPane.getTabs().add(newTab);
        }
    }
}